baseURL = 'https://example.org/'
languageCode = 'en-en_GB'
title = 'The Art of Mo'


[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
